name: 'Google Chat Action'
author: 'D Ther Htun'
description: 'Github actions for google chat Room Bot'
branding:
  icon: 'paperclip'
  color: 'blue'
inputs:
  msg: 
    description: 'Github Event Number'
    required: true
  webhook:
    description: 'Google Chat Webhook URL'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
