name: Sample Testing
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Hello world
      run: echo Hello world $FIRST_NAME $middle_name $Last_Name! $GITHUB_EVENT_NAME
      env:
        FIRST_NAME: Mona
        middle_name: The
        Last_Name: Octocat
          #   - name: Chat Setup
          #uses: docker://dther/google-chat-action:latest
          #with:
          #msg: ${{github.event.number}
          #webhook: "https://chat.googleapis.com/v1/spaces/AAAAzPcAy4s/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=MmdzluicdrdkyUAV_QwB6BzlLcIhbfrwNzxVrEllaec%3D&threadKey=git-commit"


